[package]
name = "lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
token = { version = "0.1.0", path = "../token" }
utils = { version = "0.1.0", path = "../utils" }

unicode-properties = "0.1.4"
colored = "3.0.0"
