[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
token = { version = "0.1.0", path = "../token" }
colored = "3.0.0"
ast = { version = "0.1.0", path = "../ast" }
num_enum = "0.7.5"
once_cell = "1.21.3"