[package]
name = "type_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { version = "0.1.0", path = "../ast" }
bigdecimal = "0.4.9"
token = { version = "0.1.0", path = "../token" }
utils = { version = "0.1.0", path = "../utils" }
